trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: cd 

- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: 'MSTest with default filter'
  displayName: 'dotnet build $(buildConfiguration)'

- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'customFeed'
    versionSelector: 'latestPreRelease'
    customFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/test-tools/nuget/v3/index.json'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: 'MSTest with default filter'
    failOnMinTestsNotRun: true
    minimumExpectedTests: '1'
